programs = ['AFRIK',
            'ALBAN',
            'AM ST',
            'ARAB',
            'ARTHC',
            'ASIAN',
            'ASL',
            'BULGN',
            'CANT',
            'CHIN',
            'CL CV',
            'CLSCS',
            'CMPST',
            'CMLIT',
            'CZECH',
            'DANSH',
            'DIGHT',
            'DUTCH',
            'ELANG',
            'ENGL',
            'ESL',
            'EUROP',
            'FINN',
            'FLANG',
            'FREN',
            'GERM',
            'GREEK',
            'HCOLL',
            'HEB',
            'HONRS',
            'IAS',
            'ICLND',
            'ICS',
            'IHUM',
            'ITAL',
            'JAPAN',
            'KOREA',
            'LATIN',
            'LING',
            'LT AM',
            'MESA',
            'NE LG',
            'NORWE',
            'PHIL',
            'POLSH',
            'PORT',
            'ROM',
            'RUSS',
            'SCAND',
            'SLAT',
            'SPAN',
            'SWED',
            'TESOL',
            'UNIV',
            'WELSH',
            'WS',
            'WRTG']
